baseURL = "https://www.markuskollers.de/"
languageCode = "en-US"
title = "Markus Kollers"
theme = "markus-kollers"

[params]
  customCSS = ["/css/style.css"]

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Markus Kollers"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Social
  [[params.social]]
    name = "email"
    url  = "mailto:mail@markuskollers.de"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/MaKollers"  

  [[params.social]]
    name = "github"
    url  = "https://github.com/mkollers"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/markus-kollers-4b8b2a128/"

  [[params.social]]
    name = "xing"
    url  = "https://www.xing.com/profile/Markus_Kollers"

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Markus Kollers"
    subtitle = "Software Architect and Web developer expert"
    keywords = ""
    copyright = "Markus Kollers"
    readOtherPosts = "Read other posts"
  [languages.en.params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"
  [languages.de]
    title = "Markus Kollers"
    subtitle = "Software Architekt and Experte für Webentwicklung"
    keywords = ""
    copyright = "Markus Kollers"
  [languages.de.params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"
  [languages.de.menu]
      [[languages.de.menu.main]]
        identifier = "ueber-mich"
        name = "Über mich"
        url = "/"
      [[languages.de.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
