version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: angular-build
          command: npm run build:client-and-server-bundles
     - run:
         name: angular-test
         command: npm test
#      - store_artifacts:
#          path: test-results.xml
#          prefix: tests
#      - run:
#          name: angular-lint
#          command: npm run lint -- --formatters-dir ./tslint-formatters --format junit -o tslint.xml
#      - store_artifacts:
#          path: tslint.xml
#          prefix: lint
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}