version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: angular-build
          command: ng build --prod --no-progress && ng run markuskollers-de:server:production --bundleDependencies all --no-progress
#      - run:
#          name: angular-test
#          command: npm test
#      - store_artifacts:
#          path: test-results.xml
#          prefix: tests
#      - run:
#          name: angular-lint
#          command: npm run lint -- --formatters-dir ./tslint-formatters --format junit -o tslint.xml
#      - store_artifacts:
#          path: tslint.xml
#          prefix: lint