version: 2
 jobs:
   build:
     docker:
       - image: circleci/node:8-browsers
     steps:
       - checkout
       - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
       - run: npm install
       - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"